import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { APP_TITLE } from "@/lib/constants";
import { Geist } from "next/font/google"

export const metadata: Metadata = {
  title: APP_TITLE,
  description: "Generated by create next app",
};

const geist = Geist({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={geist.className} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
